### ISSUE TITLE
No way to set java runtime parameters.

### ISSUE THREAD

**Issue by cooperaj** [dwradcliffe/chef-solr#14]
I'm having issues with solr only coming up on an IPv6 port. The way to fix this is to pass some stuff to java.

    -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true

Could I please have the ability to do this added?

**Comment by dwradcliffe** [comment]
Now you can! As of https://github.com/dwradcliffe/chef-solr/commit/b88d5df6523dd81d35a26682f9b72a195c5ca383 and `v0.4.0`.
