### ISSUE TITLE
Create solr user and group.

### ISSUE THREAD

**Issue by erikfrerejean** [dwradcliffe/chef-solr#30]
The user and group that own the `node['solr']['data_dir']` can be set through the arguments passed into the cookbook. However these variables aren't checked/created when running the tasks, meaning that if changed to for example `solr:solr` the provisioning will exit because the user doesn't exists.

It would be nice to extend the recipe, to create the user/group if they don't exist so you can override the arguments and it simply works.

**Comment by spuder** [comment]
+1 looking forward to this
