### ISSUE TITLE
problem with solr version 3.6.2

### ISSUE THREAD

**Issue by muddman** [dwradcliffe/chef-solr#9]
Thanks for providing this!

The apache archive has a different file name structure for older versions of Solr so if I set the version to 3.6.2 the default recipe fails to download the solr tgz.  The download URL for 3.6.2 is https://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.tgz and not https://archive.apache.org/dist/lucene/solr/3.6.2/solr-3.6.2.tgz.  I am able to successfully override by setting solr url to https://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.tgz.

Thanks again!

p

**Comment by mburns** [comment]
Fixed in #24.
